language: python
python: 2.7
install: 
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg install download install
  - bin/buildout -N -t 3 -c travis.cfg

script: bin/test && bin/code-analysis
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
after_failure:
  - bin/buildout annotate -c travis.cfg
